### ISSUE TITLE
Hitting other mobs besides sheep does no damage

### ISSUE THREAD

**Issue by Drullkus** [AtomicBlom/ShearMadness#1]
I'm assuming you're canceling all mob hurt events when the Chisel item is held.

Expected: Hitting horses, cows, slimes with Chisel hurts them.

Received: No damage or mob turning red occurring.

**Comment by AtomicBlom** [comment]
You're mean. I'm just saying.

**Comment by AtomicBlom** [comment]
Fixed in 1.0.1
