### ISSUE TITLE
Game Freezes from render errors after updating Chisel

### ISSUE THREAD

**Issue by The-Fireplace** [AtomicBlom/ShearMadness#31]
After updating Chisel, one of your chiseled sheep that was in my world from before updating caused the screen to keep flashing between light blue and the (frozen) game screen. I had to close it, and when I went to investigate the cause, the log was spammed with this:
http://paste.ubuntu.com/23272550/
Chisel 0.0.6.48
Shear Madness 1.2.1

**Comment by AtomicBlom** [comment]
Oh ouch. That's not good.
I'll try look into it on my lunch break today.

**Comment by AtomicBlom** [comment]
@The-Fireplace I don't suppose you'd have any idea what kind of blocks would be on the sheep would you? I'm struggling to reproduce the problem.

**Comment by The-Fireplace** [comment]
@AtomicBlom as a matter of fact, I do. It was Limestone, Raw. I'll also look in to it and see if I can figure out exactly how to reproduce it.

**Comment by The-Fireplace** [comment]
Here, I reproduced it. Full log:
http://paste.ubuntu.com/23273271/
Steps I used to reproduce: 
1. Spawn a sheep
2. Put Limestone (Raw) in a Diamond Chisel
3. Left click sheep

**Comment by AtomicBlom** [comment]
I couldn't reproduce it with Limestone, I did however manage to capture the problem using glass.

I'll release 1.2.2 tomorrow morning which should both fix your issue, and prevent further epilepsy inducing crashes by catching bad renders and replacing the model on the sheep with this:
![2016-10-04_23 18 33](https://cloud.githubusercontent.com/assets/3894692/19077278/7e4c8612-8a93-11e6-959d-8f2c71ede2e3.png)

**Comment by AtomicBlom** [comment]
Hi @The-Fireplace, There were a few delays in releasing this update, but it's out now on CurseForge and here on GitHub, feel free to try out 1.3.0, it should alleviate your issue.
