### ISSUE TITLE
Crash when Chiseling Sheep

### ISSUE THREAD

**Issue by WenXin20** [AtomicBlom/ShearMadness#33]
I crashed when I chiseled a sheep.
Chisel v0.0.6.46
Shear Madness v1.3.0
[Crash Log](http://pastebin.com/XWcs2T6A)

**Comment by AtomicBlom** [comment]
That looks like my bad. The minimum version of Chisel required is 0.0.6.52 due to changes they made in their rendering.

**Comment by WenXin20** [comment]
Ok, although I can't update chisel because there is a bug with Xaero's Minimap, which causes the game to freeze.

**Comment by AtomicBlom** [comment]
Fixed by modern versions of Shear Madness
