### ISSUE TITLE
Only getting coloured sheeps

### ISSUE THREAD

**Issue by MrAmericanMike** [AtomicBlom/ShearMadness#34]
Whenever I try to chisel a sheep I only get them changing colors.

I'm using the basic chisel with redstone blocks on it and when I left click on a sheep it just changes color.

Chisel: 0.0.7.7
ShearMadness: 1.4.0
Forge: 12.18.2.2139

Am I missing something, maybe a config or something, ot its just a bug?

Thanks a lot.

**Comment by MrAmericanMike** [comment]
Doing some tests, I went back to older versions of Chisel and it does work, just noticed that after reloading world, some redstone sheeps where back into colored sheeps.

And even more weird, now the combination mentiones above, does work. I will do more tests and keep you updated. Its weird, not sure, maybe on New worlds created with the combination above it doesnt work.

PS: Confirmed, if the world is created while using 0.0.7.7 Chisel, it wont work...

The combination 0.0.7.3 Chisel and 1.4.0 ShearMadness does works. 0.0.7.5 and above breaks and only gives colored sheeps

**Comment by AtomicBlom** [comment]
Oh that's weird. I'll look into that as soon as I can, may not be for 36 hours or so I'm afraid.

**Comment by ghost** [comment]
I had the same issue last night. Same versions (Chisel 0.0.7.7, Shear 1.4.0), I tried vanilla cobblestone and some variants.
(Trivia: Changing sheep colors changes the googly eyes color too.)

**Comment by AtomicBlom** [comment]
With apologies for the long delay, version 1.4.1 fixes the issue with Chisel 0.0.7.7

**Comment by MrAmericanMike** [comment]
Thanks a lot, gonna update both mods on my next ModPack update ;)
