### ISSUE TITLE
Crashes in 1.12.2 when chiseling sheep

### ISSUE THREAD

**Issue by smbarbour** [AtomicBlom/ShearMadness#42]
Same issue as #41, but in 1.12.2

Crashlog: https://gist.github.com/smbarbour/b682cdeecac8e5a16334888f87372894

**Comment by smbarbour** [comment]
Caused by: https://github.com/Chisel-Team/ConnectedTexturesMod/commit/9eb93e06498186a270cbb56378495d3aa4ade3c8

**Comment by smbarbour** [comment]
PR #43

**Comment by AtomicBlom** [comment]
With great apologies I forgot to release the fix until today.

It's on CurseForge as 1.7.2.4, thanks so much for helping with this.
